name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: curl -L https://api.github.com/repos/${{ github.repository }}/tarball/${{ github.sha }} > source.tar.gz
      - uses: ./
        id: upload
        with:
          path: source.tar.gz
          private-key: ${{ secrets.PRIVATE_KEY }}
          proof: ${{ secrets.PROOF }}
      - run: |
          echo "cid: ${{ steps.upload.outputs.cid }}"
      - run: exit 1
        if: ${{ !steps.upload.outputs.cid }}
